export const blogCategories = [
  { label: "Technology", value: "technology" },
  { label: "Software Development", value: "softwareDevelopment" },
  { label: "Gadgets", value: "gadgets" },
  { label: "AI and Machine Learning", value: "aiAndMachineLearning" },
  { label: "Cybersecurity", value: "cybersecurity" },
  { label: "Cloud Computing", value: "cloudComputing" },
  { label: "Blockchain", value: "blockchain" },

  { label: "Business", value: "business" },
  { label: "Entrepreneurship", value: "entrepreneurship" },
  { label: "Marketing", value: "marketing" },
  { label: "Finance", value: "finance" },
  { label: "Human Resources", value: "humanResources" },
  { label: "Startups", value: "startups" },
  { label: "Leadership", value: "leadership" },

  { label: "Lifestyle", value: "lifestyle" },
  { label: "Health and Wellness", value: "healthAndWellness" },
  { label: "Travel", value: "travel" },
  { label: "Food and Recipes", value: "foodAndRecipes" },
  { label: "Fashion", value: "fashion" },
  { label: "Home and Garden", value: "homeAndGarden" },
  { label: "Personal Development", value: "personalDevelopment" },

  { label: "Education", value: "education" },
  { label: "E-learning", value: "eLearning" },
  { label: "Language Learning", value: "languageLearning" },
  { label: "Study Tips", value: "studyTips" },
  { label: "Academic Research", value: "academicResearch" },
  { label: "Educational Technology", value: "educationalTechnology" },
  { label: "Online Courses", value: "onlineCourses" },

  { label: "Entertainment", value: "entertainment" },
  { label: "Movies", value: "movies" },
  { label: "Music", value: "music" },
  { label: "TV Shows", value: "tvShows" },
  { label: "Books", value: "books" },
  { label: "Video Games", value: "videoGames" },
  { label: "Celebrity News", value: "celebrityNews" },

  { label: "News", value: "news" },
  { label: "Current Events", value: "currentEvents" },
  { label: "Politics", value: "politics" },
  { label: "International News", value: "internationalNews" },
  { label: "Local News", value: "localNews" },
  { label: "Environment", value: "environment" },
  { label: "Science", value: "science" },

  { label: "Sports", value: "sports" },
  { label: "Football", value: "football" },
  { label: "Basketball", value: "basketball" },
  { label: "Baseball", value: "baseball" },
  { label: "Soccer", value: "soccer" },
  { label: "Olympics", value: "olympics" },
  { label: "Esports", value: "esports" },

  { label: "Art and Culture", value: "artAndCulture" },
  { label: "Art", value: "art" },
  { label: "Photography", value: "photography" },
  { label: "History", value: "history" },
  { label: "Museums", value: "museums" },
  { label: "Theater", value: "theater" },
  { label: "Cultural Critique", value: "culturalCritique" },

  { label: "Science", value: "science" },
  { label: "Biology", value: "biology" },
  { label: "Physics", value: "physics" },
  { label: "Chemistry", value: "chemistry" },
  { label: "Astronomy", value: "astronomy" },
  { label: "Environmental Science", value: "environmentalScience" },
  { label: "Research Innovations", value: "researchInnovations" },

  { label: "DIY and Crafts", value: "diyAndCrafts" },
  { label: "Crafting", value: "crafting" },
  { label: "Woodworking", value: "woodworking" },
  { label: "Home Improvement", value: "homeImprovement" },
  { label: "Sewing", value: "sewing" },
  { label: "DIY Projects", value: "diyProjects" },
  { label: "Gardening", value: "gardening" },

  { label: "Automotive", value: "automotive" },
  { label: "Car Reviews", value: "carReviews" },
  { label: "Motorcycles", value: "motorcycles" },
  { label: "Car Maintenance", value: "carMaintenance" },
  { label: "Electric Vehicles", value: "electricVehicles" },
  { label: "Motorsports", value: "motorsports" },
  { label: "Automotive Industry News", value: "automotiveIndustryNews" },

  { label: "Parenting", value: "parenting" },
  { label: "Pregnancy", value: "pregnancy" },
  { label: "Newborn Care", value: "newbornCare" },
  { label: "Child Development", value: "childDevelopment" },
  { label: "Parenting Tips", value: "parentingTips" },
  { label: "Education for Kids", value: "educationForKids" },
  { label: "Family Activities", value: "familyActivities" },

  { label: "Finance", value: "finance" },
  { label: "Personal Finance", value: "personalFinance" },
  { label: "Investing", value: "investing" },
  { label: "Real Estate", value: "realEstate" },
  { label: "Cryptocurrency", value: "cryptocurrency" },
  { label: "Budgeting", value: "budgeting" },
  { label: "Financial Planning", value: "financialPlanning" },

  { label: "Food and Drink", value: "foodAndDrink" },
  { label: "Vegan Recipes", value: "veganRecipes" },
  { label: "Baking", value: "baking" },
  { label: "Wine Tasting", value: "wineTasting" },
  { label: "Restaurant Reviews", value: "restaurantReviews" },
  { label: "Nutrition", value: "nutrition" },
  { label: "Food Trends", value: "foodTrends" },

  { label: "Health and Fitness", value: "healthAndFitness" },
  { label: "Exercise Routines", value: "exerciseRoutines" },
  { label: "Mental Health", value: "mentalHealth" },
  { label: "Nutrition", value: "nutrition" },
  { label: "Yoga", value: "yoga" },
  { label: "Weight Loss", value: "weightLoss" },
  { label: "Supplements", value: "supplements" },

  { label: "Travel", value: "travel" },
  { label: "Destinations", value: "destinations" },
  { label: "Travel Tips", value: "travelTips" },
  { label: "Budget Travel", value: "budgetTravel" },
  { label: "Adventure Travel", value: "adventureTravel" },
  { label: "Luxury Travel", value: "luxuryTravel" },
  { label: "Cultural Travel", value: "culturalTravel" },

  { label: "Green Living", value: "greenLiving" },
  { label: "Sustainability", value: "sustainability" },
  { label: "Renewable Energy", value: "renewableEnergy" },
  { label: "Eco-Friendly Products", value: "ecoFriendlyProducts" },
  { label: "Zero Waste", value: "zeroWaste" },
  { label: "Conservation", value: "conservation" },
  { label: "Organic Farming", value: "organicFarming" },

  { label: "Beauty", value: "beauty" },
  { label: "Skincare", value: "skincare" },
  { label: "Makeup", value: "makeup" },
  { label: "Haircare", value: "haircare" },
  { label: "Beauty Tips", value: "beautyTips" },
  { label: "Product Reviews", value: "productReviews" },
  { label: "Beauty Trends", value: "beautyTrends" },

  { label: "Pets", value: "pets" },
  { label: "Pet Care", value: "petCare" },
  { label: "Dog Training", value: "dogTraining" },
  { label: "Cat Behavior", value: "catBehavior" },
  { label: "Pet Health", value: "petHealth" },
  { label: "Exotic Pets", value: "exoticPets" },
  { label: "Pet Adoption", value: "petAdoption" },

  { label: "Relationships", value: "relationships" },
  { label: "Dating Advice", value: "datingAdvice" },
  { label: "Marriage Tips", value: "marriageTips" },
  { label: "Friendship", value: "friendship" },
  { label: "Family Dynamics", value: "familyDynamics" },
  { label: "Communication Skills", value: "communicationSkills" },
  { label: "Conflict Resolution", value: "conflictResolution" },

  { label: "Career", value: "career" },
  { label: "Job Search Tips", value: "jobSearchTips" },
  { label: "Resume Building", value: "resumeBuilding" },
  { label: "Career Development", value: "careerDevelopment" },
  { label: "Remote Work", value: "remoteWork" },
  { label: "Workplace Culture", value: "workplaceCulture" },
  { label: "Networking", value: "networking" },

  { label: "Creative Writing", value: "creativeWriting" },
  { label: "Poetry", value: "poetry" },
  { label: "Short Stories", value: "shortStories" },
  { label: "Writing Tips", value: "writingTips" },
  { label: "Publishing", value: "publishing" },
  { label: "Writing Prompts", value: "writingPrompts" },
  { label: "Author Interviews", value: "authorInterviews" },

  { label: "Spirituality", value: "spirituality" },
  { label: "Meditation", value: "meditation" },
  { label: "Mindfulness", value: "mindfulness" },
  { label: "Religious Studies", value: "religiousStudies" },
  { label: "Personal Growth", value: "personalGrowth" },
  { label: "Inspirational Stories", value: "inspirationalStories" },
  { label: "Spiritual Practices", value: "spiritualPractices" },

  { label: "Hobbies", value: "hobbies" },
  { label: "Collecting", value: "collecting" },
  { label: "Board Games", value: "boardGames" },
  { label: "Knitting", value: "knitting" },
  { label: "Model Building", value: "modelBuilding" },
  { label: "Photography", value: "photography" },
  { label: "Bird Watching", value: "birdWatching" },

  { label: "Technology Reviews", value: "technologyReviews" },
  { label: "Product Reviews", value: "productReviews" },
  { label: "Tech News", value: "techNews" },
  { label: "How-to Guides", value: "howToGuides" },
  { label: "Comparisons", value: "comparisons" },
  { label: "Buyer’s Guides", value: "buyersGuides" },
  { label: "Innovations", value: "innovations" },

  { label: "Legal", value: "legal" },
  { label: "Legal Advice", value: "legalAdvice" },
  { label: "Case Studies", value: "caseStudies" },
  { label: "Legal News", value: "legalNews" },
  { label: "Intellectual Property", value: "intellectualProperty" },
  { label: "Business Law", value: "businessLaw" },
  { label: "Personal Injury", value: "personalInjury" },
];
