import AppProvider from "@/hoc/app/AppProvider";
import StoreProvider from "@/hoc/app/StoreProvider";
import AppLayout from "@/layouts/AppLayout";
import "@styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Suspense } from "react";
import Loading from "./loading";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Blogger App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log("insideroot");
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <AppProvider>
            <AppLayout>
              <Suspense fallback={<Loading />}>{children}</Suspense>
              {/* <Loading /> */}
            </AppLayout>
          </AppProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
