import MainPageContainer from '@/containers/MainPageContainer';
import { Metadata } from 'next';
import Head from 'next/head';
import Image from 'next/image';

export const metadata: Metadata = {
  title: 'Feed | Blogger',
  description: 'Generated by create next app'
};

export default async function Home() {
  return (
    <>
      <MainPageContainer />
    </>
  );
}
