import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@styles/globals.css';
import StoreProvider from '@/hoc/app/StoreProvider';
import AppProvider from '@/hoc/app/AppProvider';
import { Suspense, useEffect } from 'react';
import { ToastContainer } from 'react-toastify';
import Header from '@/components/layout/Header';
import AppLayout from '@/layouts/AppLayout';
import { cookies } from 'next/headers';
import Loading from './loading';
import Head from 'next/head';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Blogger App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <AppProvider>
            <AppLayout>
              <Suspense fallback={<Loading />}>{children}</Suspense>
              {/* <Loading /> */}
            </AppLayout>
          </AppProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
