import RegisterContainer from '@/containers/auth/RegisterContainer';
import { Metadata } from 'next';
import React from 'react';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

const RegisterIndex = () => {
  return <RegisterContainer />;
};

export default RegisterIndex;
